---
galaxy_info:
  author: Keys
  description: Install Active Directory Certificate Services for LDAPS
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - adcs
    - certificate
    - ldaps

dependencies: []
