---
galaxy_info:
  author: Keys
  description: Disable Windows Firewall on SCORCH hosts
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - firewall
    - scorch

dependencies: []
