---
galaxy_info:
  author: Keys
  description: Create SCORCH service accounts and groups in Active Directory
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - scorch
    - activedirectory
    - accounts

dependencies: []
