---
galaxy_info:
  author: Keys
  description: Install SCORCH prerequisites including .NET, IIS, and VC++ Redistributable
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - scorch
    - prerequisites
    - dotnet
    - iis

dependencies: []
